export const BOOKMARK_CAPTURE_LIMITS = {
  extensionRequestBytes: 4 * 1024 * 1024,
  storedHtmlBytes: 2 * 1024 * 1024,
  fetchedHtmlBytes: 5 * 1024 * 1024,
  domElements: 50_000,
  redirects: 5,
  responseHeadersMs: 5_000,
  totalAttemptMs: 15_000,
  urlBytes: 8 * 1024,
  titleCodePoints: 1_024,
  authorCodePoints: 512,
  descriptionCodePoints: 2_048,
  siteNameCodePoints: 512,
  versionBytes: 128,
  discoveredFeeds: 16,
} as const;

export const SANITIZER_POLICY_VERSION = 1;
export const EXTENSION_BOOKMARK_CONTRACT_VERSION = 2;
export const READABILITY_EXTRACTOR_VERSION = "mozilla-readability-0.6";

export const BOOKMARK_CAPTURE_ALLOWED_TAGS = [
  "a",
  "abbr",
  "article",
  "aside",
  "b",
  "blockquote",
  "br",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "dd",
  "del",
  "details",
  "div",
  "dl",
  "dt",
  "em",
  "figcaption",
  "figure",
  "footer",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hr",
  "i",
  "img",
  "ins",
  "kbd",
  "li",
  "main",
  "mark",
  "nav",
  "ol",
  "p",
  "pre",
  "q",
  "s",
  "samp",
  "section",
  "small",
  "span",
  "strong",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "time",
  "tr",
  "u",
  "ul",
  "var",
] as const;

export const BOOKMARK_CAPTURE_ALLOWED_ATTRIBUTES = [
  "alt",
  "aria-label",
  "colspan",
  "datetime",
  "dir",
  "height",
  "href",
  "id",
  "lang",
  "open",
  "role",
  "rowspan",
  "scope",
  "src",
  "srcset",
  "title",
  "width",
  "data-serial-embed",
  "data-video-id",
  "data-start",
] as const;
